const express = require('express');
const AdminController = require('../controllers/AdminController');
const WithdrawalRequestController = require('../controllers/WithdrawalRequestController');
const SettingsController = require('../controllers/SettingsController');
const DocumentPageController = require('../controllers/DocumentPageController');
const TransactionFeeController = require('../controllers/TransactionFeeController');
const PackageController = require('../controllers/PackageController');
const authMiddleware = require('../middleware/authMiddleware');
const checkPermission = require('../middleware/checkPermission');
const supportOrAdmin = require('../middleware/supportOrAdmin');

const router = express.Router();
const adminGuard = [authMiddleware, checkPermission('admin:all')];
const supportGuard = [authMiddleware, supportOrAdmin];

router.get('/stats', adminGuard, AdminController.getStats);
router.get('/wallets', adminGuard, AdminController.getAllWallets);
router.get('/transactions', adminGuard, AdminController.getAllTransactions);
router.get('/tickets', supportGuard, AdminController.getAllTickets);
router.get('/tickets/:id/messages', supportGuard, AdminController.getTicketMessages);
router.get('/users/:id/wallets', adminGuard, AdminController.getUserWallets);
router.get('/users/:id/transactions', adminGuard, AdminController.getUserTransactions);
router.get('/withdrawals', adminGuard, WithdrawalRequestController.getAdminRequests);
router.post('/withdrawals/:id/approve', adminGuard, WithdrawalRequestController.approve);
router.post('/withdrawals/:id/reject', adminGuard, WithdrawalRequestController.reject);
router.get('/settings', adminGuard, SettingsController.getSettings);
router.post('/settings', adminGuard, SettingsController.saveSettings);
router.post('/settings/logo-upload', adminGuard, SettingsController.uploadLogo);
router.get('/transaction-fees', adminGuard, TransactionFeeController.getFees);
router.post('/transaction-fees', adminGuard, TransactionFeeController.saveFees);
router.delete('/transaction-fees/:id', adminGuard, TransactionFeeController.deleteFee);
router.get('/packages', adminGuard, PackageController.getAll);
router.post('/packages', adminGuard, PackageController.save);
router.delete('/packages/:id', adminGuard, PackageController.delete);
router.get('/subscriptions', adminGuard, AdminController.getSubscriptions);
router.get('/subscription-stats', adminGuard, AdminController.getSubscriptionStats);
router.get('/legal-pages', adminGuard, DocumentPageController.getAll);
router.post('/legal-pages', adminGuard, DocumentPageController.save);
router.delete('/legal-pages/:id', adminGuard, DocumentPageController.delete);

module.exports = router;
